---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: retry-stalled-objects
spec:
  schedule: "*/10 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: utils
            image: zenko/s3utils:0.2
            imagePullPolicy: IfNotPresent 
            command: ["/bin/bash"]
            args:
            - -c
            - node stalled.js 
            env:
            - name: ENDPOINT
              value: ""
            - name: ACCESS_KEY
              value: ""
            - name: SECRET_KEY
              value: ""
            - name: MONGODB_REPLICASET
              value: ""
            - name: DRY_RUN
              value: "false"